# Generated by Django 5.1.7 on 2025-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_cash_flow_generating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_liability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='monthly_cash_flow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('real_estate', 'Income Real Estate'), ('business', 'Business'), ('stocks', 'Dividend Stocks'), ('bonds', 'Bonds'), ('intellectual', 'Intellectual Property'), ('cash_flow', 'Cash Flow Assets'), ('cash', 'Cash'), ('bank', 'Bank Account'), ('investment', 'Investment'), ('mortgage', 'Mortgage'), ('consumer_loan', 'Consumer Loan'), ('credit_card', 'Credit Card'), ('auto_loan', 'Auto Loan'), ('lease', 'Lease Obligations'), ('other_debt', 'Other Debt'), ('other', 'Other')], default='bank', max_length=20),
        ),
    ]
