# Generated by Django 5.1.7 on 2025-03-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0003_account_is_income_source_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GEL', 'Georgian Lari'), ('RUB', 'Russian Ruble')], default='USD', max_length=3),
        ),
    ]
