# Generated by Django 5.1.7 on 2025-03-23 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0005_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_parent_budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='parent_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_budgets', to='personal_finance.budget'),
        ),
    ]
