from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    """Category for financial transactions.
    
    Args:
        name: The name of the category.
        user: The user who created the category.
        is_expense: Whether this category represents an expense.
        is_income: Whether this category represents an income.
        color: HEX color code for UI representation.
        parent: Parent category if this is a subcategory.
    """
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='subcategories')
    is_expense = models.BooleanField(default=True)
    is_income = models.BooleanField(default=False)
    color = models.CharField(max_length=7, default="#e08200")  # HEX color
    icon = models.CharField(max_length=50, blank=True, null=True)  # Icon name
    
    class Meta:
        verbose_name_plural = "Categories"
    
    def __str__(self):
        return self.name
        
    def is_subcategory(self):
        """Returns True if this is a subcategory."""
        return self.parent is not None


class Account(models.Model):
    """Financial account according to financial framework.
    
    In the financial framework:
    - Assets put money in your pocket (generate income)
    - Liabilities take money out of your pocket (generate expenses)
    - Income sources provide money in exchange for your time
    
    Args:
        name: The name of the account.
        user: The user who owns the account.
        balance: Current balance of the account.
        currency: Currency code (USD, EUR, etc).
        account_type: Type of account (real_estate, business, stocks, etc for assets;
                     mortgage, consumer_loan, etc for liabilities;
                     salary, freelance, etc for income sources).
        is_liability: Boolean flag to mark if this is a liability account.
        is_income_source: Boolean flag to mark if this is an income source.
        is_cash_flow_generating: Boolean flag to mark if this asset generates cash flow.
        monthly_cash_flow: Monthly cash flow generated by this asset.
        color: HEX color code for UI representation.
    """
    ACCOUNT_TYPES = (
        # Asset types
        ('real_estate', 'Income Real Estate'),
        ('business', 'Business'),
        ('stocks', 'Dividend Stocks'),
        ('bonds', 'Bonds'),
        ('intellectual', 'Intellectual Property'),
        ('cash_flow', 'Cash Flow Assets'),
        # Standard account types
        ('cash', 'Cash'),
        ('bank', 'Bank Account'),
        ('investment', 'Investment'),
        # Income source types
        ('salary', 'Salary'),
        ('freelance', 'Freelance'),
        ('commission', 'Commission'), 
        ('consulting', 'Consulting'),
        # Liability types
        ('mortgage', 'Mortgage'),
        ('consumer_loan', 'Consumer Loan'),
        ('credit_card', 'Credit Card'),
        ('auto_loan', 'Auto Loan'),
        ('lease', 'Lease Obligations'),
        ('other_debt', 'Other Debt'),
        ('other', 'Other'),
    )
    
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    currency = models.CharField(max_length=3, default="USD")
    account_type = models.CharField(max_length=20, choices=ACCOUNT_TYPES, default='bank')
    color = models.CharField(max_length=7, default="#1f2937")  # HEX color
    icon = models.CharField(max_length=50, blank=True, null=True)  # Icon name
    is_active = models.BooleanField(default=True)
    is_liability = models.BooleanField(default=False)
    is_income_source = models.BooleanField(default=False)
    is_cash_flow_generating = models.BooleanField(default=False)
    monthly_cash_flow = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    
    def __str__(self):
        return self.name

    def is_true_asset(self):
        """Returns True if this is a true asset (generates cash flow)."""
        return (not self.is_liability) and (not self.is_income_source) and self.is_cash_flow_generating


class Transaction(models.Model):
    """Financial transaction.
    
    Args:
        user: The user who made the transaction.
        amount: Transaction amount.
        date: Date of the transaction.
        description: Description of the transaction.
        category: Category of the transaction.
        account: Account associated with the transaction.
        is_expense: Whether this transaction is an expense.
        is_income: Whether this transaction is an income.
        is_transfer: Whether this transaction is a transfer between accounts.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    date = models.DateField()
    description = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="transactions")
    to_account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, blank=True, related_name="incoming_transfers")
    is_expense = models.BooleanField(default=True)
    is_income = models.BooleanField(default=False)
    is_transfer = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.description} - {self.amount}"


class Budget(models.Model):
    """Budget for expense categories.
    
    Args:
        user: The user who created the budget.
        category: Category this budget applies to.
        amount: Budget amount.
        currency: Currency code (USD, EUR, RUB, GEL, etc).
        month: Month for this budget (1-12).
        year: Year for this budget.
        is_parent_budget: Whether this is a parent budget (for the main category).
        parent_budget: Reference to the parent budget if this is a subcategory budget.
    """
    CURRENCY_CHOICES = (
        ('USD', 'US Dollar'),
        ('EUR', 'Euro'),
        ('GEL', 'Georgian Lari'),
        ('RUB', 'Russian Ruble'),
    )
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default="USD")
    month = models.IntegerField()  # 1-12
    year = models.IntegerField()
    is_parent_budget = models.BooleanField(default=False)
    parent_budget = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, 
                                      related_name='subcategory_budgets')
    
    class Meta:
        unique_together = ('user', 'category', 'month', 'year')
    
    def __str__(self):
        return f"{self.category.name} - {self.month}/{self.year}: {self.amount} {self.currency}"


class SavingsGoal(models.Model):
    """Savings goal.
    
    Args:
        user: The user who created the goal.
        name: Name of the goal.
        target_amount: Target amount to save.
        current_amount: Current saved amount.
        deadline: Deadline for the goal.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    target_amount = models.DecimalField(max_digits=15, decimal_places=2)
    current_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    deadline = models.DateField(null=True, blank=True)
    color = models.CharField(max_length=7, default="#f7c73a")  # HEX color
    icon = models.CharField(max_length=50, blank=True, null=True)  # Icon name
    is_achieved = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name